### PR TITLE
Optics Xi Implementation 

### PR DESCRIPTION
**Pull request by peekxc**
Prof. Hahsler, 

Please see the proposed changes to your package. I tried to mirror your methodology in determining when to call/use the xi method for hierarchical clustering. I also added some to the documentation part and example usage. If there's anything you would like to change, feel free to do so, or if you want me to change something just let me know!

### CODE REVIEW

**Comment by mhahsler** [comment]
Hi Matt,

I just checked out your changes. Please do the folowing:
- export opticsXi (in NAMESPACE)
- in the test-opticsXi: do not use elki_out_location <- 
  "~/Downloads/elki_xi_out/" (which is locally on your machine), but put 
  the needed data into inst/test_data and read it with 
  load(system.file("test_data/elki_opticsXi.rda", package = "dbscan")) 
  from there.
- you need to add opticsXi to the man page under "Usage."

The code somehow does not work for me (I use dbscan::: since opticsXi is 
not exported):

> load(system.file("test_data/test_data.rda", package = "dbscan"))
> load(system.file("test_data/elki_optics.rda", package = "dbscan"))
> 
> ### run OPTICS XI xi=0.01, eps=1.0, minPts=5
> 
> x <- test_data
> res <- optics(x, eps = 1.0,  minPts = 5)
> res <- opticsXi(res, xi=0.01, minimum=F)
> Error: could not find function "opticsXi"
> res <- dbscan:::opticsXi(res, xi=0.01, minimum=F)
> Error in start:cend : NA/NaN argument

Make sure that R CMD check runs for the package without complaining.

Thanks,
Michael

On 03/20/2016 11:20 AM, Matt Piekenbrock wrote:

> Prof. Hahsler,
> 
> Please see the proposed changes to your package. I tried to mirror your
> methodology in determining when to call/use the xi method for
> hierarchical clustering. I also added some to the documentation part and
> example usage. If there's anything you would like to change, feel free
> to do so, or if you want me to change something just let me know!
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/mhahsler/dbscan/pull/1
> 
> ```
>     Commit Summary
> ```
> - Initial optics XI commit
> - Optics Xi ELKI commit
> - Merge branch 'master' of https://github.com/mhahsler/dbscan
>   
>   ```
>   File Changes
>   ```
> - _M_ R/optics.R
>   https://github.com/mhahsler/dbscan/pull/1/files#diff-0 (6)
> - _A_ R/opticsXi.R
>   https://github.com/mhahsler/dbscan/pull/1/files#diff-1 (186)
> - _A_ inst/test_data/elki_optics_xi.rda
>   https://github.com/mhahsler/dbscan/pull/1/files#diff-2 (0)
> - _M_ man/optics.Rd
>   https://github.com/mhahsler/dbscan/pull/1/files#diff-3 (17)
> - _A_ tests/testthat/test-opticsXi.R
>   https://github.com/mhahsler/dbscan/pull/1/files#diff-4 (29)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/mhahsler/dbscan/pull/1.patch
> - https://github.com/mhahsler/dbscan/pull/1.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/mhahsler/dbscan/pull/1

## 

   Michael Hahsler
   email: michael@hahsler.net
   web: http://michael.hahsler.net

**Comment by peekxc** [comment]
Prof. Hahsler,

Please ignore the current commit, I just wanted to update my fork; I'm not
yet finished with all of the edits you mentioned. I've been adding in a few
test cases. I also fixed a few things of note; I apologize for the previous
commit, I've been using data.table
https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.pdf
as
a replacement for my data.frame operations the past couple months and I
habitually used some data.table's syntax in the code I wrote. I've
rewritten the package code to remove that dependency. I'll email you when I
have finished the edits!

Thank you for your time,

On Mon, Mar 21, 2016 at 9:38 AM, Codecov notifications@github.com wrote:

> Current coverage
> https://codecov.io/github/mhahsler/dbscan?ref=fa77a193c67c02fe0270fec97b7b21a00992e498
> is 60.11%
> 
> Merging _#1 https://github.com/mhahsler/dbscan/pull/1_ into _master_
> will increase coverage by _+2.48%_ as of fa77a19
> https://codecov.io/github/mhahsler/dbscan/commit/fa77a193c67c02fe0270fec97b7b21a00992e498
> 
> # @@            master      #1   diff @@
> 
>   Files           28      29     +1
>   Stmts         1605    1725   +120
>   Branches         0       0
>   Methods          0       0
> ======================================+ Hit            925    1037   +112
>   Partial          0       0       - Missed         680     688     +8
> 
> Review entire Coverage Diff
> https://codecov.io/github/mhahsler/dbscan/compare/d8899ba444aa9bcf628b7198e525e4f3817f2cc9...fa77a193c67c02fe0270fec97b7b21a00992e498
> as of fa77a19
> https://codecov.io/github/mhahsler/dbscan/commit/fa77a193c67c02fe0270fec97b7b21a00992e498
> 
> Powered by Codecov https://codecov.io. Updated on successful CI builds.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/mhahsler/dbscan/pull/1#issuecomment-199282211

## 

Matt Piekenbrock
Civilian Research Assistant (CS) - AFIT
matthew.piekenbrock.ctr@afit.edu
matt.piekenbrock@gmail.com
Cell (937) 269-8582

**Comment by mhahsler** [comment]
I think you would like to see this.
http://win-builder.r-project.org/NPSFv5ORgNE6/

**Comment by peekxc** [comment]
Prof. Hahsler,

Thank you! Sorry, I didn't realize it would send an email. Trying to
double-check functionality on windows

On Mon, Mar 21, 2016 at 2:29 PM, Michael Hahsler notifications@github.com
wrote:

> I think you would like to see this.
> http://win-builder.r-project.org/NPSFv5ORgNE6/
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/mhahsler/dbscan/pull/1#issuecomment-199415077

## 

Matt Piekenbrock
Civilian Research Assistant (CS) - AFIT
matthew.piekenbrock.ctr@afit.edu
matt.piekenbrock@gmail.com
Cell (937) 269-8582

**Comment by mhahsler** [comment]
Hi Matt,

I just checked out your latest version. Looks very nice. I am not sure about the clustering that you create in the cluster element. 

Since it is hierarchical, we probably need to have some way to select where to cut. 

It would be also nice if plot produces something similar to Fig. 21 in the Optics paper (with horizontal lines depicting nested clusters).  This should be easy using a few abline calls.

-m

**Comment by peekxc** [comment]
Prof. Hahsler, 

Regarding things you mentioned: 

1) The cluster element, as you probably know, cannot contain all of the information regarding the hierarchical representation as there is often overlap between points being within multiple clusters. Rather than not changing the cluster element, I opted to create a representation of the clusters that was "cluster-maximal" so-to-say; I order the cluster by there size in descending order, and then I fill in the cluster elements iteratively. This allows for the smaller, embedded clusters (that don't have clusters within them themselves) to always be visible, while bigger clusters that contain other clusters may only be partially visible. Although the data with the test case is difficult to visualize this, I think this idea is easy to visualize in the example I added in the optics documentation, where you can see smaller clusters form inside larger ones 

2) Because of what I mentioned above, I know that of course the user should be able to access the hierarchical representation of clusters. To handle this I created the clusters_xi element which contains the start and end values (of the order element) that represent the clusters intervals. Let me know if you would like an alternative representation for this or for the above

3) I've added plotting functionality for the xi clusters. I ended up using segments rather than abline to control the lengths of the lines. Let me know what you think!

EDIT: I'm not sure what you mean by  "need to have some way to select where to cut.". Could you elaborate?

**Pull request merged**
